---
# MY PLUGINS
# ==========================================
- repo: wincent/terminus
# - repo: pelodelfuego/vim-swoop
- repo: tpope/vim-surround
- repo: godlygeek/tabular


# Icons
# ==========================================
- repo: ryanoasis/vim-devicons

# Typescript
- { repo: Quramy/tsuquyomi, on_ft: ts }
- repo: HerringtonDarkholme/yats.vim
